name: GHDL test
on: [push]
jobs:
  Run-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get GHDL
      uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: Run GHDL
      working-directory: .
      run: |
        ghdl -c test1.vhdl -r part1_tb
        