name: GHDL test
on: [push]
jobs:
  Run-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get GHDL
      uses: ghdl/setup-ghdl-ci@nightly
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run GHDL
      continue-on-error: true
      run: |
        ghdl --version
        ghdl -c test1.vhdl
        ghdl -e part1_tb
        ghdl -r part1_tb
    - name: List files in the repository
      run: |
        ls -al ${{ github.workspace }}