name: GHDL test
on: [push]
jobs:
  Run-on-Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        backend: [ '', mcode, llvm, gcc ]
        version: [ latest ]
    runs-on: ubuntu-${{ matrix.version }}
    name: '🐧 Ubuntu ${{ matrix.version }} · ${{ matrix.backend }}'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Get GHDL
      uses: ghdl/setup-ghdl-ci@nightly
      with: 
        backend: ${{ matrix.backend }}
    - name: Run GHDL
      continue-on-error: true
      run: |
        ghdl --version
        # ghdl --help
        # ghdl -c test1.vhdl
        # ghdl -e part1_tb
        # ghdl -r part1_tb
        ghdl -c test1.vhdl -r part1_tb
    - name: List files in the repository
      run: |
        ls -al ${{ github.workspace }}